# Bring up all the pieces necessary to run the workbench
# Data persists in dbdata in local dir

# This file passes through all necessary env variables to requisite
# Docker containers and makes them available when running commands via
# `docker exec`. The environment variables need to be set by the user, either
# with a .env file or some other means.

version: '3'

services:

  db:
    image: postgres:9
    container_name: cjw-db
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  web:
    image: cjworkbench/cjworkbench-main
    container_name: cjw-web
    depends_on:
      - db
    volumes:
      - importedmodules:/cjworkbench/importedmodules
      - saveddata:/cjworkbench/media

    # user must set these before running docker-compose
    env_file: /home/cjworkbench/.env

    ports:
      - "8000:8000"
    command: /cjworkbench/start-prod.sh

volumes:
    dbdata: {}
    importedmodules: {}
    saveddata: {}
