# Bring up all the pieces necessary to run the workbenc
# Data persists in dbdata in local dir

version: '3'

services:

  db:
    image: postgres:9
    environment:
      - POSTGRES_USER=cjworkbench
      - POSTGRES_PASSWORD=cjworkbench
      - POSTGRES_DB=cjworkbench
    ports:
      - "5432:5432"
    volumes:
      - ./dbdata:/var/lib/postgresql/data

  web:
    image: jonathanstray/cjworkbench
    depends_on:
      - db

    # user must set this before running docker-compose
    environment:
      - CJW_SECRET_KEY 

    ports:
      - "8000:8000"
    command: /bin/bash /cjworkbench/start-prod.sh



