version: '2'

services:

  db:
    image: postgres:9
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./dbdata:/var/lib/postgresql/data

  web:
    image: jstray/cjworkbench
    depends_on:
      - db
    ports:
      - "8000:8000"

